### ISSUE TITLE
what we have to add in this repo,is it dsa code?

### ISSUE THREAD

**Issue by Danuragtiwari** [Krushna-Prasad-Sahoo/hacktoberfest-2022#10]

**Comment by Danuragtiwari** [comment]
what we have to add in this repo,is it dsa code?
@Krushna-Prasad-Sahoo

**Comment by Krushna-Prasad-Sahoo** [comment]
Yes, @Danuragtiwari . 
You can contribute dsa codes in any language.

**Comment by Danuragtiwari** [comment]
@Krushna-Prasad-Sahoo ohhk cool!!

**Comment by Danuragtiwari** [comment]
Added check it sir
